### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by marcos-c1** [marcos-c1/Data-Structures#2]
### RoadMap of TAD

- Queues
    - [ ] Priority Queue
    - [ ] Simple Queue
    - [ ] Circular Queue

- Stack
    - [ ] LIFO (Last in first out)
    - [ ] FILO (First in last out)

- Lists
     - [ ] Linked List
     - [ ] Double Linked List
     - [ ] Circular Linked List

- Trees
     - [ ] BST
     - [ ] AVL

- Heap
     - [ ] Max-Heap
     - [ ] Min-Heap

- Hash
    - [ ] HashMap
    - [ ] HashSet
